### ISSUE TITLE
Repo / README renovation

### ISSUE THREAD

**Issue by Phate6660** [Phate6660/crust#13]
So, I have a few things planned:
- Rename the project (to either rush or crust)
- Update the README to use a format that supports embeds*
- Create a logo and/or mascot for the project (I'll be making them in Blender/GIMP)

\* I don't really want to go with the standard markdown or rst to be honest.
In my opinion, it should be something simple with minimal/plaintext styling by default, but can be more robust.

Pinging @TheOnAndOnlyZenomat for any opinions.

**Comment by Phate6660** [comment]
I just got an idea.
The fully finished version of:
![preview](https://cdn.fosstodon.org/media_attachments/files/107/073/019/441/421/174/original/97b29cfd0690df67.png)

As the mascot, then to go in the readme we can have a fancy plaintext logo.

**Comment by TheOnAndOnlyZenomat** [comment]
Looking good 👍

**Comment by Phate6660** [comment]
I have the start of a README renovation here: https://github.com/Phate6660/crusty/tree/repo-renovation
What do you think about it?

**Comment by Phate6660** [comment]
Hmmm I never closed this. I believe this should be done now. :D
Will re-open if anything else needs to be renovated.

**Comment by Phate6660** [comment]
Re-opening this issue now as a reminder to update the README.
There are a few different features I forgot to add.
For example, you worked hard on the prompt functionality yet it's not mentioned anywhere.

**Comment by Phate6660** [comment]
I think it should be updated now. :D
