### ISSUE TITLE
Builtins print their own output after piping

### ISSUE THREAD

**Issue by TheOnAndOnlyZenomat** [Phate6660/crust#28]
I noticed, that builtins print their own output, even after piping.
e.g.:
```bash
echo hello | figlet
```
prints
```
 _          _ _                            _     _
| |__   ___| | | ___   __      _____  _ __| | __| |
| '_ \ / _ \ | |/ _ \  \ \ /\ / / _ \| '__| |/ _` |
| | | |  __/ | | (_) |  \ V  V / (_) | |  | | (_| |
|_| |_|\___|_|_|\___/    \_/\_/ \___/|_|  |_|\__,_|


hello world | figlet
```

This doesn't happen with `/usr/bin/echo`, and I also tested with ls and calc. So I guess,that they handle their arguments, but don't stop at the redirection char.

**Comment by Phate6660** [comment]
That is actually a good point.
I knew that in the back of my mind, but didn't really think about it.
I'll look through the code and see what's up.
Obviously if there's a bigger issue at large it needs to be fixed.

**Comment by Phate6660** [comment]
> looking at the code I think they shouldn't know about anything after the redirection mark, because we split the input string

You're definitely right. We split the input here at lines `285`-`290` of `src/shared_functions`:
```rust
let parts = input.args.split(|arg| {
    arg == &String::from("|")  ||
    // Check for appending first because `>` would match both.
    arg == &String::from(">>") ||
    arg == &String::from(">")
 });
```
----
Wait I think I see the issue.
I'm pretty sure it's due to:
```rust
    if idx == 0 {
        let command = ShellCommand {
            name: input.name.clone(),
            args: part[0..].to_vec(),
            redirection: get_redirection_type(input)
        };
        commands.push(command);
    } else {
        let command = ShellCommand {
            name: part[0].clone(),
            args: part[1..].to_vec(),
            redirection: get_redirection_type(input)
        }
    }
```
The `[0..]` and `[1..]` is making it grab **all** elements after the specified one.
We need to instead find where each redirection/pipe is and only take up to the end of each section.
I think. I could be completely wrong, I've been drinking. :D 
But this is my best guess as of right now.

**Comment by TheOnAndOnlyZenomat** [comment]
If I get the documentation right, split should return an iterator over the subslices, separated by the separator, which is not included in those splits. So, if I don't mess this up mentally, the `part` variable should not include anything, after the split. But let me check that

**Comment by TheOnAndOnlyZenomat** [comment]
Yeah, `part` does only include the stuff relevant to it's own command. It doesn't know about anything after the redirection char. I suspect, that the first command gets run regardless of redirection, so let me look into that.

**Comment by TheOnAndOnlyZenomat** [comment]
Found it! It is, because the match statement in the `run` function first matches all the builtins and then runs the piping. Fixing it right now
